SKILL_TAXONOMY = {
    # Programming Languages
    "python":          {"category": "Programming", "level": "core",     "resources": [("Python for Everybody - Coursera", "https://coursera.org/specializations/python"), ("Automate the Boring Stuff (free)", "https://automatetheboringstuff.com")]},
    "java":            {"category": "Programming", "level": "core",     "resources": [("Java Programming - MOOC.fi (free)", "https://java-programming.mooc.fi"), ("Java Masterclass - Udemy", "https://udemy.com/course/java-the-complete-java-developer-course")]},
    "javascript":      {"category": "Programming", "level": "core",     "resources": [("The Odin Project (free)", "https://theodinproject.com"), ("javascript.info (free)", "https://javascript.info")]},
    "typescript":      {"category": "Programming", "level": "core",     "resources": [("TypeScript Handbook (free)", "https://typescriptlang.org/docs/handbook/intro.html"), ("Total TypeScript (free tier)", "https://totaltypescript.com")]},
    "c++":             {"category": "Programming", "level": "core",     "resources": [("learncpp.com (free)", "https://learncpp.com"), ("C++ Primer (book)", "https://www.amazon.com/dp/0321714113")]},
    "go":              {"category": "Programming", "level": "core",     "resources": [("Tour of Go (free)", "https://go.dev/tour"), ("Go by Example (free)", "https://gobyexample.com")]},
    "rust":            {"category": "Programming", "level": "advanced", "resources": [("The Rust Book (free)", "https://doc.rust-lang.org/book"), ("Rustlings (free)", "https://github.com/rust-lang/rustlings")]},
    # ML / AI
    "machine learning": {"category": "ML/AI", "level": "core",     "resources": [("ML Specialization - Coursera (Andrew Ng)", "https://coursera.org/specializations/machine-learning-introduction"), ("fast.ai Practical ML (free)", "https://course.fast.ai")]},
    "deep learning":    {"category": "ML/AI", "level": "advanced",  "resources": [("Deep Learning Specialization - Coursera", "https://coursera.org/specializations/deep-learning"), ("MIT 6.S191 (free)", "https://introtodeeplearning.com")]},
    "nlp":              {"category": "ML/AI", "level": "advanced",  "resources": [("HuggingFace NLP Course (free)", "https://huggingface.co/learn/nlp-course"), ("Stanford CS224N (free)", "https://web.stanford.edu/class/cs224n")]},
    "bert":             {"category": "ML/AI", "level": "advanced",  "resources": [("HuggingFace Transformers Docs (free)", "https://huggingface.co/docs/transformers"), ("Illustrated BERT - Jay Alammar (free)", "https://jalammar.github.io/illustrated-bert")]},
    "tensorflow":       {"category": "ML/AI", "level": "advanced",  "resources": [("TensorFlow Tutorials (free)", "https://tensorflow.org/tutorials"), ("Deep Learning with Python (book)", "https://www.manning.com/books/deep-learning-with-python")]},
    "pytorch":          {"category": "ML/AI", "level": "advanced",  "resources": [("PyTorch Tutorials (free)", "https://pytorch.org/tutorials"), ("fast.ai (uses PyTorch, free)", "https://course.fast.ai")]},
    "scikit-learn":     {"category": "ML/AI", "level": "core",      "resources": [("Scikit-learn User Guide (free)", "https://scikit-learn.org/stable/user_guide.html"), ("Hands-on ML with Scikit-Learn (book)", "https://oreilly.com/library/view/hands-on-machine-learning/9781492032632")]},
    "langchain":        {"category": "ML/AI", "level": "advanced",  "resources": [("LangChain Docs (free)", "https://python.langchain.com"), ("LangChain Crash Course - YouTube", "https://youtube.com/watch?v=lG7Uxts9SXs")]},
    "huggingface":      {"category": "ML/AI", "level": "advanced",  "resources": [("HuggingFace Course (free)", "https://huggingface.co/learn/nlp-course"), ("HuggingFace Docs (free)", "https://huggingface.co/docs")]},
    "spacy":            {"category": "ML/AI", "level": "core",      "resources": [("spaCy Course (free)", "https://course.spacy.io"), ("spaCy Docs (free)", "https://spacy.io/usage")]},
    "opencv":           {"category": "ML/AI", "level": "core",      "resources": [("OpenCV Python Tutorials (free)", "https://docs.opencv.org/4.x/d6/d00/tutorial_py_root.html"), ("PyImageSearch Blog (free)", "https://pyimagesearch.com")]},
    "generative ai":    {"category": "ML/AI", "level": "advanced",  "resources": [("Google GenAI Course (free)", "https://ai.google.dev/gemini-api/docs"), ("Prompt Engineering Guide (free)", "https://promptingguide.ai")]},
    "statistics":       {"category": "ML/AI", "level": "core",      "resources": [("StatQuest - YouTube (free)", "https://youtube.com/@statquest"), ("Khan Academy Statistics (free)", "https://khanacademy.org/math/statistics-probability")]},
    # Web / Backend
    "react":            {"category": "Web Dev", "level": "core",    "resources": [("React Official Docs (free)", "https://react.dev/learn"), ("Full Stack Open (free)", "https://fullstackopen.com")]},
    "vue":              {"category": "Web Dev", "level": "core",    "resources": [("Vue Official Guide (free)", "https://vuejs.org/guide/introduction.html"), ("Vue Mastery (free tier)", "https://vuemastery.com")]},
    "node.js":          {"category": "Web Dev", "level": "core",    "resources": [("Node.js Learn (free)", "https://nodejs.org/en/learn"), ("The Odin Project (free)", "https://theodinproject.com")]},
    "fastapi":          {"category": "Web Dev", "level": "core",    "resources": [("FastAPI Tutorial (free)", "https://fastapi.tiangolo.com/tutorial"), ("FastAPI Full Course - YouTube", "https://youtube.com/watch?v=7t2alSnE2-I")]},
    "flask":            {"category": "Web Dev", "level": "core",    "resources": [("Flask Mega-Tutorial (free)", "https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world"), ("Flask Docs (free)", "https://flask.palletsprojects.com")]},
    "django":           {"category": "Web Dev", "level": "core",    "resources": [("Django Official Tutorial (free)", "https://docs.djangoproject.com/en/5.0/intro/tutorial01"), ("Django for Beginners (book)", "https://djangoforbeginners.com")]},
    # Databases
    "sql":              {"category": "Databases", "level": "core",    "resources": [("SQLZoo (free)", "https://sqlzoo.net"), ("Mode SQL Tutorial (free)", "https://mode.com/sql-tutorial")]},
    "mysql":            {"category": "Databases", "level": "core",    "resources": [("MySQL Tutorial (free)", "https://mysqltutorial.org"), ("MySQL Docs (free)", "https://dev.mysql.com/doc")]},
    "mongodb":          {"category": "Databases", "level": "core",    "resources": [("MongoDB University (free)", "https://learn.mongodb.com"), ("MongoDB Docs (free)", "https://www.mongodb.com/docs/manual")]},
    "postgresql":       {"category": "Databases", "level": "core",    "resources": [("PostgreSQL Tutorial (free)", "https://postgresqltutorial.com"), ("PostgreSQL Docs (free)", "https://postgresql.org/docs")]},
    "redis":            {"category": "Databases", "level": "core",    "resources": [("Redis University (free)", "https://university.redis.com"), ("Redis Docs (free)", "https://redis.io/docs")]},
    # DevOps / Cloud
    "docker":           {"category": "DevOps", "level": "core",      "resources": [("Docker Getting Started (free)", "https://docs.docker.com/get-started"), ("TechWorld with Nana - Docker (YouTube)", "https://youtube.com/watch?v=3c-iBn73dDE")]},
    "kubernetes":       {"category": "DevOps", "level": "advanced",  "resources": [("Kubernetes Basics (free)", "https://kubernetes.io/docs/tutorials/kubernetes-basics"), ("KodeKloud K8s Free Tier", "https://kodekloud.com/courses/kubernetes-for-the-absolute-beginners-hands-on")]},
    "aws":              {"category": "Cloud",   "level": "core",     "resources": [("AWS Skill Builder (free)", "https://skillbuilder.aws"), ("AWS Cloud Practitioner Essentials", "https://aws.amazon.com/training/learn-about/cloud-practitioner")]},
    "azure":            {"category": "Cloud",   "level": "core",     "resources": [("Microsoft Learn Azure (free)", "https://learn.microsoft.com/en-us/training/azure"), ("AZ-900 Study Guide (free)", "https://learn.microsoft.com/en-us/certifications/azure-fundamentals")]},
    "gcp":              {"category": "Cloud",   "level": "core",     "resources": [("Google Cloud Skills Boost (free)", "https://cloudskillsboost.google"), ("GCP Associate Engineer Prep", "https://cloud.google.com/learn/certification/cloud-engineer")]},
    "git":              {"category": "DevOps",  "level": "core",     "resources": [("Pro Git Book (free)", "https://git-scm.com/book/en/v2"), ("Learn Git Branching (interactive, free)", "https://learngitbranching.js.org")]},
    "linux":            {"category": "DevOps",  "level": "core",     "resources": [("Linux Journey (free)", "https://linuxjourney.com"), ("The Linux Command Line (free)", "https://linuxcommand.org/tlcl.php")]},
    # Data
    "pandas":           {"category": "Data", "level": "core",        "resources": [("Pandas Tutorials (free)", "https://pandas.pydata.org/docs/getting_started/intro_tutorials"), ("Kaggle Pandas Course (free)", "https://kaggle.com/learn/pandas")]},
    "numpy":            {"category": "Data", "level": "core",        "resources": [("NumPy Quickstart (free)", "https://numpy.org/doc/stable/user/quickstart.html"), ("NumPy for Beginners (free)", "https://numpy.org/doc/stable/user/absolute_beginners.html")]},
    "data analysis":    {"category": "Data", "level": "core",        "resources": [("freeCodeCamp Data Analysis (free)", "https://freecodecamp.org/learn/data-analysis-with-python"), ("Kaggle Learn (free)", "https://kaggle.com/learn")]},
    "hadoop":           {"category": "Data", "level": "advanced",    "resources": [("Hadoop Tutorial (free)", "https://tutorialspoint.com/hadoop"), ("Hadoop: The Definitive Guide (book)", "https://oreilly.com/library/view/hadoop-the-definitive/9781491901687")]},
    "spark":            {"category": "Data", "level": "advanced",    "resources": [("Spark Official Docs (free)", "https://spark.apache.org/docs/latest"), ("Databricks Free Training", "https://www.databricks.com/learn/training/home")]},
    "power bi":         {"category": "Data", "level": "core",        "resources": [("Microsoft Power BI Learning (free)", "https://learn.microsoft.com/en-us/training/powerplatform/power-bi"), ("Guy in a Cube - YouTube (free)", "https://youtube.com/@GuyInACube")]},
    "tableau":          {"category": "Data", "level": "core",        "resources": [("Tableau Training (free)", "https://www.tableau.com/learn/training"), ("Tableau for Beginners - YouTube", "https://youtube.com/watch?v=TPMlZxRRaBQ")]},
}

